### ISSUE TITLE
Understanding SNPWeight Column and Conversion to Effect Size Estimation

### ISSUE THREAD

**Issue by CSGallagher** [fastlmm/FaST-LMM#27]
As I mentioned in a previous thread (https://github.com/fastlmm/FaST-LMM/issues/25), we a currently running case/control association analyses with FastLMM's single_snp function. We want to check our understanding of the "SNPWeight" output column. In the method section of this paper (https://www.biorxiv.org/content/10.1101/639955v2.full.pdf) specifically in the section in the attached image, the authors use an equation to convert the SNPweight estimate into an effect size estimate for a quantitative trait. We did not come across anything in the FastLMM manual that indicates a conversion is necessary. Does the "SNPWeight" output column need to be converted into an effect size estimate in order to obtain a beta that's comparable to standard linear regression? If it is in the manual, apologies in advance for missing it! Thank you so much!
![Screen Shot 2022-03-10 at 4 50 55 PM](https://user-images.githubusercontent.com/60437500/157781132-cfabeb07-abb1-4987-8d0d-dfda58780733.png)

**Comment by CarlKCarlK** [comment]
Scott,

We have a new version of single_snp that we'd love for you to try. It replaces the non-standard SnpFractVarExpl with EffectWeight.

To install:
pip uninstall fastlmm
pip install ***@***.***

Meaning of output columns:


  *   SNPWeight is the beta for the "standardized test SNP" (where "standardized" means made to have mean 0, stdev 1)
  *   EffectWeight is SNPWeight ^2 * "raw" test SNP variance / phenotype variance,  where
     *   "raw" means the original test SNP values of "0,1,2" (the count of allele 1 or 2 [it doesn't matter])
     *   The phenotype's original values are used (so, they are not, for example, changed by regressing out the covariates)


Does this make sense?
Is it what you need?


  *   Carl

From: Carl K
Sent: Monday, March 14, 2022 3:23 PM
To: fastlmm/FaST-LMM ***@***.***>; fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: RE: [fastlmm/FaST-LMM] Understanding SNPWeight Column and Conversion to Effect Size Estimation (Issue #27)

Scott,

Thanks for your question. We're working on an answer.


  *   Carl

From: c scott gallagher ***@***.******@***.***>>
Sent: Thursday, March 10, 2022 4:59 PM
To: fastlmm/FaST-LMM ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [fastlmm/FaST-LMM] Understanding SNPWeight Column and Conversion to Effect Size Estimation (Issue #27)
Importance: High


As I mentioned in a previous thread (#25<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffastlmm%2FFaST-LMM%2Fissues%2F25&data=04%7C01%7C%7Ca887a1735c2f4a2fd01c08da02fa61e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825571713534895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=87DUizCLEsfZWzs9r7OHDkFRC%2FMiicObdkIBzLPM8%2F8%3D&reserved=0>), we a currently running case/control association analyses with FastLMM's single_snp function. We want to check our understanding of the "SNPWeight" output column. In the method section of this paper (https://www.biorxiv.org/content/10.1101/639955v2.full.pdf<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.biorxiv.org%2Fcontent%2F10.1101%2F639955v2.full.pdf&data=04%7C01%7C%7Ca887a1735c2f4a2fd01c08da02fa61e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825571713534895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=w6QvO45c2jpIhdo%2B2RdCH31FBC2QEhwDZLSwD5PyqkQ%3D&reserved=0>) specifically in the section in the attached image, the authors use an equation to convert the SNPweight estimate into an effect size estimate for a quantitative trait. We did not come across anything in the FastLMM manual that indicates a conversion is necessary. Does the "SNPWeight" output column need to be converted into an effect size estimate in order to obtain a beta that's comparable to standard linear regression? If it is in the manual, apologies in advance for missing it! Thank you so much!
[Screen Shot 2022-03-10 at 4 50 55 PM]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F60437500%2F157781132-cfabeb07-abb1-4987-8d0d-dfda58780733.png&data=04%7C01%7C%7Ca887a1735c2f4a2fd01c08da02fa61e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825571713534895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7MQ58F2Lf9lAljads8dQrTRPecge2HeO8ZzaBG%2FncJU%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffastlmm%2FFaST-LMM%2Fissues%2F27&data=04%7C01%7C%7Ca887a1735c2f4a2fd01c08da02fa61e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825571713534895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XgTS5VRQVWt1l%2FVmowDea%2FR9jt1wxdIiwdXk8e2FgGU%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABR65PZRXKIF6DF4QR2AEX3U7KLGVANCNFSM5QOHIJNA&data=04%7C01%7C%7Ca887a1735c2f4a2fd01c08da02fa61e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825571713534895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GIpo7YAigTZ2UcoCFQIBZjB633nllXsHyTWIsURFWKU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca887a1735c2f4a2fd01c08da02fa61e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825571713534895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=y%2BAgo6F9c06UNGlkzQsaUpg%2B6%2FI4sjgBOZc3MD3Mgz8%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca887a1735c2f4a2fd01c08da02fa61e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825571713534895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p6jQSl5n%2BmeaCarQjlHX4Epjyj85sZoRIG%2BC8fEqZn8%3D&reserved=0>.

**Comment by CarlKCarlK** [comment]
Whoops. In the output it is "EffectSize" (not EffectWeight)

From: Carl K ***@***.***>
Sent: Wednesday, March 16, 2022 2:17 PM
To: fastlmm/FaST-LMM ***@***.***>; fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>; ***@***.***
Subject: [fastlmm-dev] Re: [fastlmm/FaST-LMM] Understanding SNPWeight Column and Conversion to Effect Size Estimation (Issue #27)
Importance: High

Scott,

We have a new version of single_snp that we'd love for you to try. It replaces the non-standard SnpFractVarExpl with EffectWeight.

To install:
pip uninstall fastlmm
pip install ***@***.***

Meaning of output columns:


  *   SNPWeight is the beta for the "standardized test SNP" (where "standardized" means made to have mean 0, stdev 1)
  *   EffectSize is SNPWeight ^2 * "raw" test SNP variance / phenotype variance,  where
     *   "raw" means the original test SNP values of "0,1,2" (the count of allele 1 or 2 [it doesn't matter])
     *   The phenotype's original values are used (so, they are not, for example, changed by regressing out the covariates)


Does this make sense?
Is it what you need?


  *   Carl

From: Carl K
Sent: Monday, March 14, 2022 3:23 PM
To: fastlmm/FaST-LMM ***@***.******@***.***>>; fastlmm/FaST-LMM ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: RE: [fastlmm/FaST-LMM] Understanding SNPWeight Column and Conversion to Effect Size Estimation (Issue #27)

Scott,

Thanks for your question. We're working on an answer.


  *   Carl

From: c scott gallagher ***@***.******@***.***>>
Sent: Thursday, March 10, 2022 4:59 PM
To: fastlmm/FaST-LMM ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [fastlmm/FaST-LMM] Understanding SNPWeight Column and Conversion to Effect Size Estimation (Issue #27)
Importance: High


As I mentioned in a previous thread (#25<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffastlmm%2FFaST-LMM%2Fissues%2F25&data=04%7C01%7C%7Cdc4d1ea96baa4371058f08da0792566e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637830622347742440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oQmLTLfKByHo4dg2TDzn3XuA%2FpTpyFCBviVwHM%2BbaB0%3D&reserved=0>), we a currently running case/control association analyses with FastLMM's single_snp function. We want to check our understanding of the "SNPWeight" output column. In the method section of this paper (https://www.biorxiv.org/content/10.1101/639955v2.full.pdf<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.biorxiv.org%2Fcontent%2F10.1101%2F639955v2.full.pdf&data=04%7C01%7C%7Cdc4d1ea96baa4371058f08da0792566e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637830622347742440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0OFgnkfUUBHLMJKYui7vQFZuj7fRN%2Fon6drs4KfAY8c%3D&reserved=0>) specifically in the section in the attached image, the authors use an equation to convert the SNPweight estimate into an effect size estimate for a quantitative trait. We did not come across anything in the FastLMM manual that indicates a conversion is necessary. Does the "SNPWeight" output column need to be converted into an effect size estimate in order to obtain a beta that's comparable to standard linear regression? If it is in the manual, apologies in advance for missing it! Thank you so much!
[Screen Shot 2022-03-10 at 4 50 55 PM]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F60437500%2F157781132-cfabeb07-abb1-4987-8d0d-dfda58780733.png&data=04%7C01%7C%7Cdc4d1ea96baa4371058f08da0792566e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637830622347742440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NKQCNR%2F3FjAYCatTcrcUMtawiS5eU6ceq1bCvUXe4j0%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffastlmm%2FFaST-LMM%2Fissues%2F27&data=04%7C01%7C%7Cdc4d1ea96baa4371058f08da0792566e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637830622347742440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iFtD7D3rPTjufdWhIGVRBIrXSao6qRwvr%2FU3RzR2qbA%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABR65PZRXKIF6DF4QR2AEX3U7KLGVANCNFSM5QOHIJNA&data=04%7C01%7C%7Cdc4d1ea96baa4371058f08da0792566e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637830622347742440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xU4sEkvsCvPQpebXhMET5McIvYCOR4EGMygbv3Ij6Ts%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cdc4d1ea96baa4371058f08da0792566e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637830622347742440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=o2SaGLe8sOSpa6rNQmk0jpYLUGlio5S8I3z7A%2B6T0gg%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cdc4d1ea96baa4371058f08da0792566e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637830622347898661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dBx1x%2BMvIF1vHz4IRRE4683mMuh8lx94ACIiVZXhOTY%3D&reserved=0>.

**Comment by CarlKCarlK** [comment]
Scott,

If you can, let me if your proposed change looks like what you need. Thanks.

- Carl

**Comment by CarlKCarlK** [comment]
Scott,

Thanks for your question. We're working on an answer.


  *   Carl

From: c scott gallagher ***@***.***>
Sent: Thursday, March 10, 2022 4:59 PM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] Understanding SNPWeight Column and Conversion to Effect Size Estimation (Issue #27)
Importance: High


As I mentioned in a previous thread (#25<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffastlmm%2FFaST-LMM%2Fissues%2F25&data=04%7C01%7C%7Ca887a1735c2f4a2fd01c08da02fa61e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825571713534895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=87DUizCLEsfZWzs9r7OHDkFRC%2FMiicObdkIBzLPM8%2F8%3D&reserved=0>), we a currently running case/control association analyses with FastLMM's single_snp function. We want to check our understanding of the "SNPWeight" output column. In the method section of this paper (https://www.biorxiv.org/content/10.1101/639955v2.full.pdf<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.biorxiv.org%2Fcontent%2F10.1101%2F639955v2.full.pdf&data=04%7C01%7C%7Ca887a1735c2f4a2fd01c08da02fa61e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825571713534895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=w6QvO45c2jpIhdo%2B2RdCH31FBC2QEhwDZLSwD5PyqkQ%3D&reserved=0>) specifically in the section in the attached image, the authors use an equation to convert the SNPweight estimate into an effect size estimate for a quantitative trait. We did not come across anything in the FastLMM manual that indicates a conversion is necessary. Does the "SNPWeight" output column need to be converted into an effect size estimate in order to obtain a beta that's comparable to standard linear regression? If it is in the manual, apologies in advance for missing it! Thank you so much!
[Screen Shot 2022-03-10 at 4 50 55 PM]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F60437500%2F157781132-cfabeb07-abb1-4987-8d0d-dfda58780733.png&data=04%7C01%7C%7Ca887a1735c2f4a2fd01c08da02fa61e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825571713534895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7MQ58F2Lf9lAljads8dQrTRPecge2HeO8ZzaBG%2FncJU%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffastlmm%2FFaST-LMM%2Fissues%2F27&data=04%7C01%7C%7Ca887a1735c2f4a2fd01c08da02fa61e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825571713534895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XgTS5VRQVWt1l%2FVmowDea%2FR9jt1wxdIiwdXk8e2FgGU%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABR65PZRXKIF6DF4QR2AEX3U7KLGVANCNFSM5QOHIJNA&data=04%7C01%7C%7Ca887a1735c2f4a2fd01c08da02fa61e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825571713534895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GIpo7YAigTZ2UcoCFQIBZjB633nllXsHyTWIsURFWKU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca887a1735c2f4a2fd01c08da02fa61e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825571713534895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=y%2BAgo6F9c06UNGlkzQsaUpg%2B6%2FI4sjgBOZc3MD3Mgz8%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca887a1735c2f4a2fd01c08da02fa61e8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637825571713534895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p6jQSl5n%2BmeaCarQjlHX4Epjyj85sZoRIG%2BC8fEqZn8%3D&reserved=0>.
