### ISSUE TITLE
epistatis test error

### ISSUE THREAD

**Issue by snowformatics** [fastlmm/FaST-LMM#29]
Hi everyone,

I am trying to run the epistasis function

bed_fn = Bed("my_bed_file")
pheno_fn = Pheno("my_pheno_file")
G0 = bed_fn
results_df = epistasis(bed_fn, pheno_fn, G0)

But I am getting this error:
# of pairs is 90831968705226
filling in the cache_file and log_delta, as needed
Precomputing eigen
Saving precomputation to .working\cache_file.npz
searching for internal delta
Traceback (most recent call last):
  File "C:/Users/x/PycharmProjects/x/lmm/lmm01.py", line 40, in <module>
    results_df = epistasis(bed_fn, pheno_fn, G0)
  File "C:\Users\x\AppData\Local\Continuum\anaconda3\envs\gwas_flow\lib\site-packages\fastlmm\association\epistasis.py", line 114, in epistasis
    epistasis.fill_in_cache_file()
  File "C:\Users\x\AppData\Local\Continuum\anaconda3\envs\gwas_flow\lib\site-packages\fastlmm\association\epistasis.py", line 450, in fill_in_cache_file
    lmm.sety(self.pheno['vals'])
  File "C:\Users\x\AppData\Local\Continuum\anaconda3\envs\gwas_flow\lib\site-packages\pysnptools\snpreader\snpreader.py", line 525, in __getitem__
    iid_indexer, snp_indexer = iid_indexer_and_snp_indexer
ValueError: too many values to unpack (expected 2)

I am using 
fastlmm 0.5.5 on Windows 10 and Python 3.7.

single_snp with the same data works as expected. Any ideas what I did wrong? BTW, the links to the Notebooks on the GitHub page are not working,would be nice to have them again :)

Thanks a lot
Stefanie

</body>
</html>

**Comment by CarlKCarlK** [comment]
Stefanie,

Thanks for your note!

I think the first thing to think about is the number of pairs you would like it to evaluate. It is saying that there are           90,831,968,705,226 pairs (that is, 91 trillion). Even if it could evaluate 1 million pairs per second, 91 trillion pairs would take 3 years. Also, your pvalue would need to be roughly 1e-16 to be significant.

I think this is the number of pairs from about 10M SNPs. Does that sound right? (We once did all pairs from about 400,000 SNPs, but that required a cluster and many days.)

If you want to see what happens when you run on fewer pairs, you can use the sid_list_0 and sid_list_1 inputs to restrict the number of SNPs used to make pairs. See https://fastlmm.github.io/FaST-LMM/#epistasis

Yours,
Carl


From: snowformatics ***@***.***>
Sent: Saturday, April 02, 2022 3:17 AM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] epistatis test error (Issue #29)
Importance: High


Hi everyone,

I am trying to run the epistasis function

bed_fn = Bed("my_bed_file")
pheno_fn = Pheno("my_pheno_file")
G0 = bed_fn
results_df = epistasis(bed_fn, pheno_fn, G0)

But I am getting this error:

of pairs is 90831968705226

filling in the cache_file and log_delta, as needed
Precomputing eigen
Saving precomputation to .working\cache_file.npz
searching for internal delta
Traceback (most recent call last):
File "C:/Users/x/PycharmProjects/x/lmm/lmm01.py", line 40, in
results_df = epistasis(bed_fn, pheno_fn, G0)
File "C:\Users\x\AppData\Local\Continuum\anaconda3\envs\gwas_flow\lib\site-packages\fastlmm\association\epistasis.py", line 114, in epistasis
epistasis.fill_in_cache_file()
File "C:\Users\x\AppData\Local\Continuum\anaconda3\envs\gwas_flow\lib\site-packages\fastlmm\association\epistasis.py", line 450, in fill_in_cache_file
lmm.sety(self.pheno['vals'])
File "C:\Users\x\AppData\Local\Continuum\anaconda3\envs\gwas_flow\lib\site-packages\pysnptools\snpreader\snpreader.py", line 525, in getitem
iid_indexer, snp_indexer = iid_indexer_and_snp_indexer
ValueError: too many values to unpack (expected 2)

I am using
fastlmm 0.5.5 on Windows 10 and Python 3.7.

single_snp with the same data works as expected. Any ideas what I did wrong? BTW, the links to the Notebooks on the GitHub page are not working,would be nice to have them again :)

Thanks a lot
Stefanie

-

**Comment by snowformatics** [comment]
Thanks Carl! Ok that makes of course sense, I have >10 Mil SNPs. I will try to reduce the number by filtering the p-value from the lmm results. One more question, do I have to set both,  sid_list_0 and sid_list_1? 
Thanks

**Comment by snowformatics** [comment]
I created a new bed file with about 300 SNPs but I still getting the same error:

# of pairs is 50403
filling in the cache_file and log_delta, as needed
Precomputing eigen
Saving precomputation to .working\cache_file.npz
searching for internal delta
vals
Traceback (most recent call last):
  File "C:/Users/x/PycharmProjects/BCC_Experiments/lmm/lmm01.py", line 40, in <module>
    results_df = epistasis(bed_fn, pheno_fn, G0)
  File "C:\Users\x\AppData\Local\Continuum\anaconda3\envs\gwas_flow\lib\site-packages\fastlmm\association\epistasis.py", line 114, in epistasis
    epistasis.fill_in_cache_file()
  File "C:\Users\x\AppData\Local\Continuum\anaconda3\envs\gwas_flow\lib\site-packages\fastlmm\association\epistasis.py", line 452, in fill_in_cache_file
    lmm.sety(self.pheno['vals'])
  File "C:\Users\x\AppData\Local\Continuum\anaconda3\envs\gwas_flow\lib\site-packages\pysnptools\snpreader\snpreader.py", line 526, in __getitem__
    iid_indexer, snp_indexer = iid_indexer_and_snp_indexer
ValueError: too many values to unpack (expected 2)

Do I have to prepare the bed and pheno file in a different format (single_snp  works)?

Thanks

**Comment by CarlKCarlK** [comment]
I think I found the solution to this problem. The epistatis function is older than

**Comment by CarlKCarlK** [comment]
[whoops. Sent too early. Trying again.]


I think I found the solution to the "ValueError: too many values to unpack (expected 2)" problem. The epistasis function is older than single_snp. It does not accept a Pheno reader as its phenotype input. Instead, the input must either be a phenotype file or special Python dictionary. Here is some sample code that shows how to convert a Pheno reader into the special dictionary:
from pysnptools.snpreader import Pheno
pheno = Pheno(pheno_fn)
pheno_dict = {'iid':pheno.iid, 'vals':pheno.read().val[:,0]}

# run epistasis analysis
results_df = epistasis(test_snps, pheno_dict, G0=G0, covar=cov_fn)

**Comment by CarlKCarlK** [comment]
Here is some sample code that shows the example from the notebook https://nbviewer.org/github/fastlmm/FaST-LMM/blob/master/doc/ipynb/FaST-LMM.ipynb
except that first it runs single_snp and then it keeps only SNPs with a PValue < 1e-7 for epistasis.
(I picked the cutoff arbitrarily and it's creating G0 and testing on SNPs from the same chromosome, so you may not want to something different.)


  *   Carl

# set some ipython notebook properties
%matplotlib inline

# set degree of verbosity (adapt to INFO for more verbose output)
import logging
logging.basicConfig(level=logging.WARNING)

# set figure sizes
import pylab
pylab.rcParams['figure.figsize'] = (10.0, 8.0)
#pylab.plot([1,2,3],[4,5,6])

# set display width for pandas data frames
import pandas as pd
pd.set_option('display.width', 1000)

# import the algorithm and reader
import numpy as np
from fastlmm.association import epistasis, single_snp
from pysnptools.snpreader import Bed
from fastlmm.util import example_file # Download and return local file name
from pysnptools.snpreader import Pheno

# define file names
bed_fn = example_file('tests/datasets/synth/all.*','*.bed')
bed_reader = Bed(bed_fn, count_A1=True)
pheno_fn = example_file("tests/datasets/synth/pheno_10_causals.txt")
cov_fn = example_file("tests/datasets/synth/cov.txt")
pheno = Pheno(pheno_fn)

df_single = single_snp(test_snps=bed_reader, pheno=pheno, covar=cov_fn)
print(df_single)

pvalue_cutoff = 1e-7
snp_list = list(df_single[df_single.PValue<pvalue_cutoff].SNP)
print(snp_list)

G0 = bed_reader
test_snps = bed_reader

pheno_dict = {'iid':pheno.iid, 'vals':pheno.read().val[:,0]}

# run epistasis analysis
results_df = epistasis(test_snps, pheno_dict, G0=G0, covar=cov_fn, sid_list_0=snp_list, sid_list_1=snp_list)

# qq plot
from fastlmm.util.stats import plotp
plotp.qqplot(results_df["PValue"].values, xlim=[0,5], ylim=[0,5])

# print head of results data frame
pd.set_option('display.width', 1000)
results_df.head(n=10)



From: Carl K
Sent: Sunday, April 03, 2022 5:30 PM
To: 'fastlmm/FaST-LMM' ***@***.***>; 'fastlmm/FaST-LMM' ***@***.***>
Cc: 'Comment' ***@***.***>; ***@***.***' ***@***.***>
Subject: RE: [fastlmm/FaST-LMM] epistatis test error (Issue #29)

[whoops. Sent too early. Trying again.]


I think I found the solution to the "ValueError: too many values to unpack (expected 2)" problem. The epistasis function is older than single_snp. It does not accept a Pheno reader as its phenotype input. Instead, the input must either be a phenotype file or special Python dictionary. Here is some sample code that shows how to convert a Pheno reader into the special dictionary:
from pysnptools.snpreader import Pheno
pheno = Pheno(pheno_fn)
pheno_dict = {'iid':pheno.iid, 'vals':pheno.read().val[:,0]}

# run epistasis analysis
results_df = epistasis(test_snps, pheno_dict, G0=G0, covar=cov_fn)

**Comment by snowformatics** [comment]
Hi Carl.

I have no idea how to express my deep gratitude, it works now ;) Let's cross fingers to find something interesting,
Thanks again Carl!
Stefanie

**Comment by CarlKCarlK** [comment]
Happy to help. Thanks for using FaST-LMM. Good luck.
