### ISSUE TITLE
Calculate heritability

### ISSUE THREAD

**Issue by snowformatics** [fastlmm/FaST-LMM#44]
Hi, 

Is it possible to calculate heritabilty of the LMM?  

Thanks

**Comment by CarlKCarlK** [comment]
[also sent via email]
> Is it possible to calculate heritabilty of the LMM?

I believe single_snp’s “Nullh2” output column is heritability. By default, it is calculated on every chromosome excluding the chromosome of the tested SNP. (So, leave-one-out chromosome; on human data, calculated 22 times).

When you set leave_out_one_chrom to False, heritability (Nullh2) is calculated using all SNPs, including those on the same chromosome as the SNP being tested.

For accurate p-values, you typically want to leave the leave_out_one_chrom parameter set to its default (True). However, if you want a heritability estimate that includes all chromosomes (a more global estimate), you can set leave_out_one_chrom to False. Remember, the p-values from this run might not be suitable for significance testing due to the potential for inflated statistics.

-- Carl

**Comment by snowformatics** [comment]
Thanks a lot Carl, I will check!
