### ISSUE TITLE
ValueError: No individual observed for the SNP

### ISSUE THREAD

**Issue by AbestSG** [fastlmm/FaST-LMM#53]
Hello,

I got "ValueError: No individual observed for the SNP" when I ran the fastlmm. I attached the phenotype. Could you please help me with the issue?

Thanks,
Si

import numpy as np
from fastlmm.association import single_snp
from pysnptools.snpreader import Pheno, Bed
bed = Bed(r"HCP_imputed_filtered.bed",count_A1=False)
pheno = Pheno("HCP_test_one.txt")
results_df = single_snp(bed, pheno, count_A1=False)

  **File "/data/mprc_data3/freeware/anaconda3/lib/python3.11/site-packages/pysnptools/standardizer/standardizer.py", line 153, in _standardize_unit_and_beta
    standardize_f64(
ValueError: No individual observed for the SNP.**

print(bed.iid)
[['0' '101_257946']
 ['0' '101_962058']
 ['0' '102_571144']
 ...
 ['555' '618952']
 ['998' '114823']
 ['999' '580751']]

[HCP_test_one.txt](https://github.com/user-attachments/files/16506417/HCP_test_one.txt)

**Comment by CarlKCarlK** [comment]
Thanks for using FaST-LMM!

This is usually caused by data that contains a SNP for which all the data is missing. That could happen because the individual id's (iid) in the Bed file and Pheno file don't match and therefore the intersection of matching iids is none.

If you look in your HCP_imputed_filtered.fam file, I think you'll see some columns like:
`0 101_257946 more stuff`
where you likely want
`101 257946 more stuff`
so that you match your pheno file.

If this is the problem, the fam file is just a text file, so you can fix it with a text editor or you can go back and figure out why it got generated this way.

Let me know if this helped.

Yours,
Carl

Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team
(Microsoft Research, retired)
Join the FaST-LMM user discussion and announcement list [via email](mailto:fastlmm-user-join@python.org?subject=Subscribe) (or use [web sign up](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C540f44c603f74286262e08d7bf9aa5bc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637188543563267798&sdata=yLg%2FFSbov8heBrDG0d4WAYZd%2B%2BkSjoZZMGrkYUZAD3I%3D&reserved=0))

**Comment by AbestSG** [comment]
> Thanks for using FaST-LMM!
> 
> This is usually caused by data that contains a SNP for which all the data is missing. That could happen because the individual id's (iid) in the Bed file and Pheno file don't match and therefore the intersection of matching iids is none.
> 
> If you look in your HCP_imputed_filtered.fam file, I think you'll see some columns like: `0 101_257946 more stuff` where you likely want `101 257946 more stuff` so that you match your pheno file.
> 
> If this is the problem, the fam file is just a text file, so you can fix it with a text editor or you can go back and figure out why it got generated this way.
> 
> Let me know if this helped.
> 
> Yours, Carl
> 
> Carl Kadie, Ph.D. FaST-LMM & PySnpTools Team (Microsoft Research, retired) Join the FaST-LMM user discussion and announcement list [via email](mailto:fastlmm-user-join@python.org?subject=Subscribe) (or use [web sign up](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C540f44c603f74286262e08d7bf9aa5bc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637188543563267798&sdata=yLg%2FFSbov8heBrDG0d4WAYZd%2B%2BkSjoZZMGrkYUZAD3I%3D&reserved=0))

Thank you! It's working now.
