### ISSUE TITLE
update fastlmm package in bioconda channel

### ISSUE THREAD

**Issue by JorgeHB14** [fastlmm/FaST-LMM#54]
Hi,

I am trying to create a snakemake rule for my gwas analysis using fastlmm. 

My strategy is to create an environment for that rule and therefore I am trying to dowload fastlmm using bioconda channel.

I have seen that the latest version there is the 0.2.32, this supposes a problem for me as it is stated python version < 2.8 should be used.

Do you think you can update the fastlmm version in bioconda? If it is not possible, I will try another workaround.

![image](https://github.com/user-attachments/assets/22b878ad-2ffa-43c1-8240-f172459f867f)

Best,
Jorge

**Comment by CarlKCarlK** [comment]
Hi Jorge,

Thank you for using FaST-LMM!

Thanks also for reaching out about the Bioconda recipe. We appreciate you bringing this issue to our attention.

We weren’t aware that FaST-LMM was listed on Bioconda. Someone else created the recipe. You’re right that the current listing (version 0.2.32) is outdated and tied to Python 2, which is no longer supported. The latest version of FaST-LMM, as listed on PyPI, requires Python 3.10 to 3.13. (Would this Python requirement pose any issues for your workflow?)

Since we don't know much about Bioconda, do you have suggestions on updating the listing?

Yours,
Carl

Carl Kadie, Ph.D.
[FaST-LMM & PySnpTools Team](https://fastlmm.github.io/)
(Microsoft Research, retired)
https://medium.com/@carlmkadie
https://www.linkedin.com/in/carlk/
Join the FaST-LMM user discussion and announcement list [via email](mailto:fastlmm-user-join@python.org?subject=Subscribe) (or use [web sign up](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0))

**Comment by JorgeHB14** [comment]
Hi Carl,

Sorry for the late response, forgot about this.

I have no idea how to update a biocanda recipe, sorry!

For anyone who wants to use fastlmm in a snakemake pipeline, I managed to run it creating a virtual environment for it.

Here is a yml file for the virtual environment

    name: fastlmm_env
    channels:
      - conda-forge
      - bioconda
      - defaults
    dependencies:
      - python=3.12  # Python version working for snakemake and fastlmm latest version
      - snakemake=8.25.3 # Latest version as for November 2024
      - pip 
      - pip:
        - fastlmm==0.6.12 # Latest version as for November 2024

**Comment by CarlKCarlK** [comment]
Thanks for figuring this out!
